- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=172.31.0.22
  args:
    chdir: /home/kube
    creates: /home/kube/cluster_initialized.txt

- name: create .kube directory
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755
    owner: kube

- name: copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube

- name: install Pod network
  become: yes
  become_user: kube
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    chdir: $HOME

- name: Get the token for joining the worker nodes
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command

- debug:
    msg: "{{ kubernetes_join_command.stdout }}"

#- name: Copy join command to local file.
#  become: yes
#  delegate_to: localhost
#  copy:
#    content: "{{ kubernetes_join_command.stdout_lines[0] }}"
#    dest: "kubernetes_join_command"
#    mode: 0777
