---
galaxy_info:
  role_name: k8s
  namespace: noahtkeller
  author: Noah Keller
  description: K8s Cluster Role
  min_ansible_version: 2.3.1.0
  license: Apache 2.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
    - name: Rocky
      versions:
        - 8
  galaxy_tags:
    - container
